//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36323
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenPhotosynth.RichClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenPhotosynth.RichClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;Photosynth REST API Demo&lt;/h1&gt;
        ///    &lt;p&gt;This application demonstrates how to use the Photosynth REST API in conjunction with Microsoft Account for authentication to create a desktop application
        ///    for uploading images to create Technical Preview Photosynths. You can use this code as a basis to create your own. For example, you could provide creative
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose up to {0} photos for your Photosynth.
        /// </summary>
        internal static string ChoosePhotos {
            get {
                return ResourceManager.GetString("ChoosePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} photos chosen. You may choose up to {1} more..
        /// </summary>
        internal static string ChosenPhotosStatus {
            get {
                return ResourceManager.GetString("ChosenPhotosStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not sign in..
        /// </summary>
        internal static string CouldNotSignIn {
            get {
                return ResourceManager.GetString("CouldNotSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not sign out..
        /// </summary>
        internal static string CouldNotSignOut {
            get {
                return ResourceManager.GetString("CouldNotSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;You can upload a maximum of {0} photos&quot;.
        /// </summary>
        internal static string MaxUploadWarning {
            get {
                return ResourceManager.GetString("MaxUploadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet connection..
        /// </summary>
        internal static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get user info (are you registered at Photosynth.net?).
        /// </summary>
        internal static string NotPhotosynthUser {
            get {
                return ResourceManager.GetString("NotPhotosynthUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in to continue..
        /// </summary>
        internal static string NotSignedIn {
            get {
                return ResourceManager.GetString("NotSignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion is sideways relative to the shooting direction, you are making a panorama if your shooting path is curved and you are shooting away from some point behind you..
        /// </summary>
        internal static string PanoDescription {
            get {
                return ResourceManager.GetString("PanoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed in..
        /// </summary>
        internal static string SignedIn {
            get {
                return ResourceManager.GetString("SignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in....
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in....
        /// </summary>
        internal static string SigningIn {
            get {
                return ResourceManager.GetString("SigningIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing out....
        /// </summary>
        internal static string SigningOut {
            get {
                return ResourceManager.GetString("SigningOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion is sideways relative to the shooting direction, you are making a spin if your shooting path is curved and you are generally pointing toward some central location..
        /// </summary>
        internal static string SpinDescription {
            get {
                return ResourceManager.GetString("SpinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion is basically forward relative to the direction of shooting..
        /// </summary>
        internal static string WalkDescription {
            get {
                return ResourceManager.GetString("WalkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion is sideways relative to the shooting direction, but is neither a spin nor a pano..
        /// </summary>
        internal static string WallDescription {
            get {
                return ResourceManager.GetString("WallDescription", resourceCulture);
            }
        }
    }
}
